Branch1
ABI-Documenation/scaffoldmaker-documentation pull request #2
Opened 2021-02-06 04:07 UTC by fpan017

2021-02-06 04:07 UTC, fpan017 commented
first commit

2021-02-08 11:23 UTC, PrasadBabarendaGamage requested changes
Excellent documentation @fpan017! Please see the minor comments attached.

2021-02-08 11:23 UTC, PrasadBabarendaGamage commented on docs/source/tutorials/visualising_scaffolds/visualising_scaffolds.rst
> +You may found some meshes are quite big. If you see part of the mesh exceeds the coordinates system's limitation and disappears on screen,
"If part or all of the mesh is not visible in the field of view of the scaffoldmaker's graphics viewport, you can rescale the mesh by holding ....

2021-02-08 11:23 UTC, PrasadBabarendaGamage commented on docs/source/installation.rst
> -  :caption: Contents:
Best to leave this as contents to be consistent?

2021-02-08 11:23 UTC, PrasadBabarendaGamage commented on docs/source/tutorials/creating_meshtype/creating_3d_cube.rst
> +First, go to where you put :file:`scaffoldmaker`, find the :file:`.\\src\\scaffoldmaker\\meshtypes` folder. This is where you put all mesh types.
First, navigate to where you installed scaffoldmaker, ...

2021-02-08 11:23 UTC, PrasadBabarendaGamage commented on docs/source/tutorials/creating_meshtype/creating_3d_cube.rst
> +Continue from above, we then initialize the mesh and define our interpolation function
Continuing

2021-02-08 11:23 UTC, PrasadBabarendaGamage commented on docs/source/tutorials/creating_meshtype/creating_3d_cube.rst
> +field parameter mapping and interpolation over an element. If you want to use aa interpolation function that is not included in :ref:`utils`,
aa -> a

2021-02-08 11:23 UTC, PrasadBabarendaGamage commented on docs/source/tutorials/creating_meshtype/creating_3d_cube.rst
> +you may have to manually set-up eft using basic functions provided by `Zinc <http://opencmiss.org/zinc/latest/classes.html>`_.
set-up->set up for British English
eft?

2021-02-08 11:23 UTC, PrasadBabarendaGamage commented on docs/source/tutorials/creating_meshtype/creating_3d_cube.rst
> +the structure of each element. At last, we use :pyth:`defineField` to define the field components
At last, -> Finally,

2021-02-08 11:23 UTC, PrasadBabarendaGamage commented on docs/source/tutorials/creating_meshtype/creating_3d_cube.rst
> +generates mesh in the second direction, i.e, along node 1 and node 3. :pyth:`dx_ds3` is the derivatives corresponding to the third
generates a mesh

2021-02-08 11:23 UTC, PrasadBabarendaGamage commented on docs/source/tutorials/creating_meshtype/creating_3d_tube.rst
> +Therefore we should set-up the user interface options as followed:
set-up->set up for British English

2021-02-08 11:23 UTC, PrasadBabarendaGamage commented on docs/source/tutorials/creating_meshtype/creating_3d_tube.rst
> +Everything is pretty similar to what we have done in the :ref:`3D cube <cube>` tutorial. Feel free to add your own options or constraints.
remove the word "pretty"
Best if we don't add any extra adjectives as they are not typically used in scientific writing

2021-02-08 11:23 UTC, PrasadBabarendaGamage commented on docs/source/tutorials/creating_meshtype/creating_3d_tube.rst
> +last iteration of :pyth:`e3`, nodes should return to the starting position. Thus I subtracted :pyth:`totalNodes`
Thus I -> Thus we

2021-02-08 11:23 UTC, PrasadBabarendaGamage commented on docs/source/tutorials/creating_meshtype/creating_3d_tube.rst
> +to picture this, check the figure below for better understanding.
check the figure below for better understanding ->see the figure below for more information.

2021-02-08 11:23 UTC, PrasadBabarendaGamage commented on docs/source/tutorials/visualising_scaffolds/visualising_scaffolds.rst
> +In this example, we will visualize a scaffold, modify it using user interface, and then export its nodal parameters.
modify it using user interface -> modify it using the existing user interface

2021-02-08 11:23 UTC, PrasadBabarendaGamage commented on docs/source/tutorials/visualising_scaffolds/visualising_scaffolds.rst
> +Once you have successfully installed and executed a new workflow, you should see ``scaffoldmaker`` window open.
you should see [the]

2021-02-08 11:23 UTC, PrasadBabarendaGamage commented on docs/source/tutorials/visualising_scaffolds/visualising_scaffolds.rst
> +Often, there are more than one version of parameter set
of the parameter set

2021-02-11 02:43 UTC, merged